-- NetHack inventory item prototypes for Factorio 2.0
-- One item per object tile (~456 items), used for inventory sync.
-- Icons are individual PNGs generated by convert_tiles.py.

local TC = require("scripts.tile_config")

local items = {}
local ICON_DIR = "__nethack-factorio__/graphics/icons/objects/"

for i, name in ipairs(TC.object_names) do
  items[#items + 1] = {
    type = "item",
    name = "nh-item-" .. name,
    localised_name = name:gsub("-", " "),
    icon = ICON_DIR .. "nh-item-" .. name .. ".png",
    icon_size = 32,
    stack_size = 1,
    flags = {"not-stackable", "hide-from-bonus-gui"},
    hidden = true,
    hidden_in_factoriopedia = true,
  }
end

data:extend(items)
