-- display.lua: Manages Factorio surfaces, tiles, and entities to render the NetHack dungeon
-- Uses tile_idx from glyph2tile[] for sprite selection. NetHack's core handles visibility
-- via glyph substitution (dark rooms, unlit corridors, stone) before print_glyph is called,
-- so tile_idx already encodes the correct light/dark variant.
local Display = {}

-- Callback for notifying when new entity types appear (set by main.lua)
Display.on_new_entity_type = nil

-- Tile configuration (generated by convert_tiles.py)
local TC = require("scripts.tile_config")

-- NetHack map dimensions
local MAP_W = 80
local MAP_H = 21

-- Characters that represent walls
local WALL_CHARS = {
  [string.byte("-")] = true,
  [string.byte("|")] = true,
}

-- Characters that represent doors
local DOOR_CHARS = {
  [string.byte("+")] = true,
}

-- Characters that represent stairs
local STAIR_CHARS = {
  [string.byte("<")] = true,
  [string.byte(">")] = true,
}

-- Glyph special flags (from NetHack glyph_info.gm.glyphflags)
local MG_MONSTER  = 0x0001
local MG_PET      = 0x0002
local MG_DETECT   = 0x0004
local MG_INVIS    = 0x0008
local MG_STATUE   = 0x0010
local MG_OBJPILE  = 0x0020
local MG_BW_LAVA  = 0x0040
local MG_BW_ICE   = 0x0080
local MG_BW_WATER = 0x0100

-- Map tile_idx to entity name using the tile category boundaries and name arrays
function Display.tile_entity_name(tile_idx)
  if tile_idx < TC.n_monsters then
    return "nh-mon-" .. TC.monster_names[tile_idx + 1]
  elseif tile_idx < TC.n_monsters + TC.n_objects then
    return "nh-obj-" .. TC.object_names[tile_idx - TC.n_monsters + 1]
  else
    return "nh-other-" .. TC.other_names[tile_idx - TC.n_monsters - TC.n_objects + 1]
  end
end

-- Check if a glyph special flag is set
local function has_flag(special, flag)
  return special and bit32.band(special, flag) ~= 0
end

-- Pet tint color (slight green)
local PET_TINT = {r=0.5, g=1.0, b=0.5, a=1}
-- Detected monster tint (slight cyan)
local DETECT_TINT = {r=0.5, g=1.0, b=1.0, a=1}

-- NetHack color indices -> Factorio RGB for ASCII mode
local NH_COLORS = {
  [0]  = {r=0.2, g=0.2, b=0.2},  -- black
  [1]  = {r=1, g=0, b=0},         -- red
  [2]  = {r=0, g=0.8, b=0},       -- green
  [3]  = {r=0.6, g=0.4, b=0.1},   -- brown
  [4]  = {r=0.3, g=0.3, b=1},     -- blue
  [5]  = {r=0.8, g=0, b=0.8},     -- magenta
  [6]  = {r=0, g=0.8, b=0.8},     -- cyan
  [7]  = {r=0.7, g=0.7, b=0.7},   -- gray
  [8]  = {r=1, g=1, b=1},         -- no-color/default
  [9]  = {r=1, g=0.5, b=0},       -- orange
  [10] = {r=0, g=1, b=0},         -- bright green
  [11] = {r=1, g=1, b=0},         -- yellow
  [12] = {r=0.5, g=0.5, b=1},     -- bright blue
  [13] = {r=1, g=0.3, b=1},       -- bright magenta
  [14] = {r=0.3, g=1, b=1},       -- bright cyan
  [15] = {r=1, g=1, b=1},         -- white
}

function Display.init()
  if not storage.nh_display then
    storage.nh_display = {
      levels = {},          -- level_name -> { surface_name, grid }
      current_level = nil,  -- current level name
      player_pos = {x = 0, y = 0},
      entity_map = {},      -- [level_name][y][x] -> entity reference data
      ascii_mode = false,   -- true = colored ASCII text, false = tile sprites
      text_objects = {},    -- [level_name][y][x] -> render object id (ASCII mode)
    }
  end
  -- Migration: ensure fields exist on saves from older versions
  local disp = storage.nh_display
  if disp.ascii_mode == nil then disp.ascii_mode = false end
  if not disp.text_objects then disp.text_objects = {} end
end

-- Create or get a dungeon level surface
function Display.get_or_create_level(level_name)
  local disp = storage.nh_display
  if disp.levels[level_name] then
    return game.surfaces[disp.levels[level_name].surface_name]
  end

  local surface_name = "nh-" .. level_name
  local surface = game.create_surface(surface_name, {
    default_enable_all_autoplace_controls = false,
    property_expression_names = {
      cliffiness = 0,
      ["enemy-base-frequency"] = 0,
      ["enemy-base-radius"] = 0,
      ["enemy-base-intensity"] = 0,
    },
    autoplace_settings = {
      entity = { treat_missing_as_default = false },
      tile = { treat_missing_as_default = false },
      decorative = { treat_missing_as_default = false },
    },
    width = MAP_W * 2 + 4,
    height = MAP_H * 2 + 4,
    starting_area = 0,
  })

  -- Request chunk generation for the play area
  surface.request_to_generate_chunks({x = MAP_W / 2, y = MAP_H / 2}, 3)
  surface.force_generate_chunk_requests()

  -- Fill the entire surface with void tiles (surface is centered on origin)
  local half_w = math.ceil((MAP_W * 2 + 4) / 2)
  local half_h = math.ceil((MAP_H * 2 + 4) / 2)
  local tiles = {}
  for y = -half_h, half_h do
    for x = -half_w, half_w do
      tiles[#tiles + 1] = {name = "nh-void", position = {x = x, y = y}}
    end
  end
  surface.set_tiles(tiles)

  -- Disable day/night cycle - always bright
  surface.always_day = true

  disp.levels[level_name] = {
    surface_name = surface_name,
    grid = {},  -- [y][x] = {tile_idx, ch, color, special}
  }
  disp.entity_map[level_name] = {}
  disp.text_objects[level_name] = {}

  return surface
end

-- Switch to a dungeon level
function Display.switch_level(level_name, player)
  local disp = storage.nh_display
  local surface = Display.get_or_create_level(level_name)
  disp.current_level = level_name
  if Display.on_new_entity_type then Display.on_new_entity_type() end

  if player then
    local pos = disp.player_pos
    player.teleport({x = pos.x + 0.5, y = pos.y + 0.5}, surface)
  end

  return surface
end

-- Get current surface
function Display.get_current_surface()
  local disp = storage.nh_display
  if not disp.current_level then return nil end
  local level = disp.levels[disp.current_level]
  if not level then return nil end
  return game.surfaces[level.surface_name]
end

-- Destroy entity at a grid position if one exists
local function destroy_entity_at(level_name, x, y)
  local disp = storage.nh_display
  local emap = disp.entity_map[level_name]
  if not emap then return end
  if not emap[y] then return end
  local ent_data = emap[y][x]
  if ent_data and ent_data.entity and ent_data.entity.valid then
    ent_data.entity.destroy()
  end
  if emap[y] then
    emap[y][x] = nil
  end
end

-- Destroy text render object at a grid position (ASCII mode)
local function destroy_text_at(level_name, x, y)
  local disp = storage.nh_display
  local tmap = disp.text_objects[level_name]
  if not tmap then return end
  if not tmap[y] then return end
  local obj = tmap[y][x]
  if obj and obj.valid then
    obj.destroy()
  end
  tmap[y][x] = nil
end

-- Place a colored ASCII character at a grid position (ASCII mode)
local function place_text(surface, level_name, x, y, ch, color)
  local disp = storage.nh_display
  if not disp.text_objects[level_name] then
    disp.text_objects[level_name] = {}
  end
  if not disp.text_objects[level_name][y] then
    disp.text_objects[level_name][y] = {}
  end
  destroy_text_at(level_name, x, y)

  local obj = rendering.draw_text{
    text = string.char(ch),
    surface = surface,
    target = {x = x + 0.5, y = y + 0.5},
    color = NH_COLORS[color] or {r=1, g=1, b=1},
    scale = 2.5,
    alignment = "center",
    vertical_alignment = "middle",
    font = "nh-mono",
    draw_on_ground = true,
  }
  disp.text_objects[level_name][y][x] = obj
end

-- Restore the entity at a grid position from stored grid data.
-- Used when the entity was suppressed (e.g., hero standing on it) and needs to reappear.
local function restore_entity_from_grid(surface, level_name, x, y)
  local disp = storage.nh_display
  local level = disp.levels[level_name]
  if not level then return end
  local row = level.grid[y]
  local cell = row and row[x]
  if not cell then return end
  local ent_name = Display.tile_entity_name(cell.tile_idx)
  local tint = nil
  if has_flag(cell.special, MG_PET) then
    tint = PET_TINT
  elseif has_flag(cell.special, MG_DETECT) then
    tint = DETECT_TINT
  end
  -- Inline place_entity to avoid forward reference
  destroy_entity_at(level_name, x, y)
  local ent = surface.create_entity{
    name = ent_name,
    position = {x = x + 0.5, y = y + 0.5},
    force = "player",
  }
  if ent then
    if tint then ent.color = tint end
    if not disp.entity_map[level_name][y] then
      disp.entity_map[level_name][y] = {}
    end
    disp.entity_map[level_name][y][x] = {entity = ent, name = ent_name}
  end
end

-- Place or update an entity at grid position
local function place_entity(surface, level_name, x, y, entity_name, tint)
  local disp = storage.nh_display
  destroy_entity_at(level_name, x, y)

  local ent = surface.create_entity{
    name = entity_name,
    position = {x = x + 0.5, y = y + 0.5},
    force = "player",
  }

  if ent then
    if tint then
      ent.color = tint
    end

    if not disp.entity_map[level_name][y] then
      disp.entity_map[level_name][y] = {}
    end
    disp.entity_map[level_name][y][x] = {
      entity = ent,
      name = entity_name,
    }
  end

  return ent
end

-- Resolve a bk_tile_idx to a Factorio base tile name.
-- bk_tile_idx comes from glyph2tile[bkglyph] where bkglyph encodes the
-- ground type (room, corridor, pool, lava, etc.) underneath entities.
-- Map tile names to Factorio base tiles
local TILE_NAME_MAP = {
  pool = "nh-water",
  water = "nh-water",
  ["molten-lava"] = "nh-lava",
  ice = "nh-water",  -- ice over water
}

local function resolve_base_tile(bk_tile_idx)
  if bk_tile_idx and bk_tile_idx >= 0 then
    local other_base = TC.n_monsters + TC.n_objects
    if bk_tile_idx >= other_base then
      local name = TC.other_names[bk_tile_idx - other_base + 1]
      if name then return TILE_NAME_MAP[name] or "nh-floor" end
    end
  end
  return "nh-floor"
end

-- Core function: handle a print_glyph call from NetHack
-- tile_idx = glyph2tile[glyph] index for sprite selection
-- ch = ASCII character, color = color index, special = glyphflags
-- bk_tile_idx = glyph2tile[bkglyph] for the ground under this glyph (-1 = none)
function Display.print_glyph(x, y, tile_idx, ch, color, special, bk_tile_idx)
  local disp = storage.nh_display
  if not disp.current_level then return end

  local level_name = disp.current_level
  local level = disp.levels[level_name]
  local surface = game.surfaces[level.surface_name]
  if not surface then return end

  -- Store grid state
  if not level.grid[y] then level.grid[y] = {} end
  local old = level.grid[y][x]
  level.grid[y][x] = {tile_idx = tile_idx, ch = ch, color = color, special = special, bk_tile_idx = bk_tile_idx}

  -- Skip if nothing changed
  if old and old.tile_idx == tile_idx and old.ch == ch and old.color == color
     and old.special == special and old.bk_tile_idx == bk_tile_idx then
    return
  end

  -- Resolve base tile: ASCII mode uses void (black) for all; tile mode uses bkglyph
  local base_tile
  if disp.ascii_mode then
    base_tile = "nh-void"
  elseif ch == string.byte(" ") then
    base_tile = "nh-void"
  else
    base_tile = resolve_base_tile(bk_tile_idx)
  end
  surface.set_tiles({{name = base_tile, position = {x = x, y = y}}})

  if disp.ascii_mode then
    -- ASCII mode: show colored character, no entity sprite
    destroy_entity_at(level_name, x, y)
    if ch ~= string.byte(" ") then
      place_text(surface, level_name, x, y, ch, color)
    else
      destroy_text_at(level_name, x, y)
    end
    return
  end

  -- Determine entity name from tile index
  local ent_name = Display.tile_entity_name(tile_idx)

  -- Determine tint for special effects
  local tint = nil
  if has_flag(special, MG_PET) then
    tint = PET_TINT
  elseif has_flag(special, MG_DETECT) then
    tint = DETECT_TINT
  end

  -- Always place the entity. Hero suppression is handled by set_hero_pos
  -- (called from host_curs(WIN_MAP) after all print_glyph calls in flush_screen).
  place_entity(surface, level_name, x, y, ent_name, tint)
end

-- Clear the map display grid cache, forcing all subsequent print_glyph calls
-- to update entities. Entities are preserved (not destroyed) because flush_screen
-- may not send print_glyph calls immediately (e.g., during cheat execution).
-- Positions that should become stone/void will be updated by the next print_glyph call.
function Display.clear_map()
  local disp = storage.nh_display
  if not disp.current_level then return end
  local level = disp.levels[disp.current_level]
  if not level then return end
  -- Only clear the grid cache — entities and tiles stay.
  -- print_glyph calls (whenever they arrive) will see old=nil and update everything.
  level.grid = {}
end

-- Full destructive clear: destroy all entities, fill with void tiles, reset grid.
-- Used for level transitions where a fresh surface needs to be initialized.
function Display.clear_map_full()
  local disp = storage.nh_display
  if not disp.current_level then return end

  local level_name = disp.current_level
  local level = disp.levels[level_name]
  local surface = game.surfaces[level.surface_name]
  if not surface then return end

  -- Destroy all entities
  local emap = disp.entity_map[level_name]
  if emap then
    for y, row in pairs(emap) do
      for x, ent_data in pairs(row) do
        if ent_data.entity and ent_data.entity.valid then
          ent_data.entity.destroy()
        end
      end
    end
  end
  disp.entity_map[level_name] = {}

  -- Destroy all text objects (ASCII mode)
  local tmap = disp.text_objects[level_name]
  if tmap then
    for y, row in pairs(tmap) do
      for x, obj in pairs(row) do
        if obj and obj.valid then obj.destroy() end
      end
    end
  end
  disp.text_objects[level_name] = {}

  -- Reset grid
  level.grid = {}

  -- Fill with void
  local tiles = {}
  for y = 0, MAP_H - 1 do
    for x = 0, MAP_W - 1 do
      tiles[#tiles + 1] = {name = "nh-void", position = {x = x, y = y}}
    end
  end
  surface.set_tiles(tiles)
end

-- Called from host_cliparound (in the main game loop, before each command).
-- Updates the hero position so the Factorio player character is teleported there.
-- In "factorio" player mode, destroys the hero entity so the engineer is visible,
-- and restores the entity at the previous hero position from grid data.
function Display.set_hero_pos(x, y)
  local disp = storage.nh_display
  if not disp then return end

  local old_pos = disp.player_pos
  disp.player_pos = {x = x, y = y}

  if disp.player_mode ~= "nethack" and disp.current_level then
    local level_name = disp.current_level
    local level = disp.levels[level_name]
    local surface = level and game.surfaces[level.surface_name]
    if not surface then return end

    -- Destroy entity at NEW hero position (so the engineer character is visible)
    destroy_entity_at(level_name, x, y)
    if disp.ascii_mode then
      destroy_text_at(level_name, x, y)
    end

    -- Restore at OLD hero position (it was suppressed by previous set_hero_pos)
    if old_pos and (old_pos.x ~= x or old_pos.y ~= y) then
      if disp.ascii_mode then
        -- Restore text at old position from grid data (no entity in ASCII mode)
        local row = level and level.grid[old_pos.y]
        local cell = row and row[old_pos.x]
        if cell and cell.ch ~= string.byte(" ") then
          place_text(surface, level_name, old_pos.x, old_pos.y, cell.ch, cell.color)
        end
      else
        restore_entity_from_grid(surface, level_name, old_pos.x, old_pos.y)
      end
    end
  end
end

-- Set player display mode: "factorio" (engineer visible, NH sprite hidden)
-- or "nethack" (NH sprite visible, engineer hidden via god mode).
function Display.set_player_mode(mode)
  local disp = storage.nh_display
  if not disp then return end
  disp.player_mode = mode
  -- Apply immediately to current hero position
  if disp.player_pos and disp.current_level then
    local level_name = disp.current_level
    local level = disp.levels[level_name]
    local surface = level and game.surfaces[level.surface_name]
    if surface then
      if mode == "factorio" then
        destroy_entity_at(level_name, disp.player_pos.x, disp.player_pos.y)
        if disp.ascii_mode then
          destroy_text_at(level_name, disp.player_pos.x, disp.player_pos.y)
        end
      elseif mode == "nethack" then
        if disp.ascii_mode then
          local row = level.grid[disp.player_pos.y]
          local cell = row and row[disp.player_pos.x]
          if cell and cell.ch ~= string.byte(" ") then
            place_text(surface, level_name, disp.player_pos.x, disp.player_pos.y, cell.ch, cell.color)
          end
        else
          restore_entity_from_grid(surface, level_name, disp.player_pos.x, disp.player_pos.y)
        end
      end
    end
  end
end

function Display.get_player_mode()
  local disp = storage.nh_display
  if not disp then return "factorio" end
  return disp.player_mode or "factorio"
end

-- Get the player's expected position from the display
function Display.get_player_pos()
  local disp = storage.nh_display
  return disp.player_pos
end

-- Get current level name
function Display.get_current_level()
  local disp = storage.nh_display
  return disp.current_level
end

-- Toggle between ASCII and tile display modes.
-- Returns the new ascii_mode state.
function Display.toggle_ascii_mode()
  local disp = storage.nh_display
  disp.ascii_mode = not disp.ascii_mode

  if not disp.current_level then return disp.ascii_mode end
  local level_name = disp.current_level
  local level = disp.levels[level_name]
  local surface = game.surfaces[level.surface_name]
  if not surface then return disp.ascii_mode end

  -- Re-render all cells
  local tile_batch = {}
  for y, row in pairs(level.grid) do
    for x, cell in pairs(row) do
      if disp.ascii_mode then
        -- Switch to ASCII: destroy entity, create text, set tile to void (black)
        destroy_entity_at(level_name, x, y)
        if cell.ch ~= string.byte(" ") then
          tile_batch[#tile_batch + 1] = {name = "nh-void", position = {x = x, y = y}}
          place_text(surface, level_name, x, y, cell.ch, cell.color)
        end
      else
        -- Switch to tiles: destroy text, create entity, restore base tile
        destroy_text_at(level_name, x, y)
        local base_tile = cell.ch == string.byte(" ") and "nh-void" or resolve_base_tile(cell.bk_tile_idx)
        tile_batch[#tile_batch + 1] = {name = base_tile, position = {x = x, y = y}}
        local ent_name = Display.tile_entity_name(cell.tile_idx)
        local tint = nil
        if has_flag(cell.special, MG_PET) then tint = PET_TINT
        elseif has_flag(cell.special, MG_DETECT) then tint = DETECT_TINT end
        place_entity(surface, level_name, x, y, ent_name, tint)
      end
    end
  end
  if #tile_batch > 0 then
    surface.set_tiles(tile_batch)
  end

  -- Re-apply hero suppression
  if disp.player_mode ~= "nethack" and disp.player_pos then
    local pos = disp.player_pos
    destroy_entity_at(level_name, pos.x, pos.y)
    if disp.ascii_mode then
      destroy_text_at(level_name, pos.x, pos.y)
    end
  end

  return disp.ascii_mode
end

function Display.get_ascii_mode()
  local disp = storage.nh_display
  return disp and disp.ascii_mode or false
end

return Display
