-- display.lua: Manages Factorio surfaces, tiles, and entities to render the NetHack dungeon
-- Uses tile_idx from glyph2tile[] for sprite selection. NetHack's core handles visibility
-- via glyph substitution (dark rooms, unlit corridors, stone) before print_glyph is called,
-- so tile_idx already encodes the correct light/dark variant.
local Display = {}

-- Tile configuration (generated by convert_tiles.py)
local TC = require("scripts.tile_config")

-- NetHack map dimensions
local MAP_W = 80
local MAP_H = 21

-- Characters that represent walls
local WALL_CHARS = {
  [string.byte("-")] = true,
  [string.byte("|")] = true,
}

-- Characters that represent doors
local DOOR_CHARS = {
  [string.byte("+")] = true,
}

-- Characters that represent stairs
local STAIR_CHARS = {
  [string.byte("<")] = true,
  [string.byte(">")] = true,
}

-- Glyph special flags (from NetHack glyph_info.gm.glyphflags)
local MG_MONSTER  = 0x0001
local MG_PET      = 0x0002
local MG_DETECT   = 0x0004
local MG_INVIS    = 0x0008
local MG_STATUE   = 0x0010
local MG_OBJPILE  = 0x0020
local MG_BW_LAVA  = 0x0040
local MG_BW_ICE   = 0x0080
local MG_BW_WATER = 0x0100

-- Map tile_idx to entity name using the tile category boundaries and name arrays
function Display.tile_entity_name(tile_idx)
  if tile_idx < TC.n_monsters then
    return "nh-mon-" .. TC.monster_names[tile_idx + 1]
  elseif tile_idx < TC.n_monsters + TC.n_objects then
    return "nh-obj-" .. TC.object_names[tile_idx - TC.n_monsters + 1]
  else
    return "nh-other-" .. TC.other_names[tile_idx - TC.n_monsters - TC.n_objects + 1]
  end
end

-- Pet tint color (slight green)
local PET_TINT = {r=0.5, g=1.0, b=0.5, a=1}
-- Detected monster tint (slight cyan)
local DETECT_TINT = {r=0.5, g=1.0, b=1.0, a=1}

function Display.init()
  if not storage.nh_display then
    storage.nh_display = {
      levels = {},          -- level_name -> { surface_name, grid }
      current_level = nil,  -- current level name
      player_pos = {x = 0, y = 0},
      entity_map = {},      -- [level_name][y][x] -> entity reference data
    }
  end
end

-- Create or get a dungeon level surface
function Display.get_or_create_level(level_name)
  local disp = storage.nh_display
  if disp.levels[level_name] then
    return game.surfaces[disp.levels[level_name].surface_name]
  end

  local surface_name = "nh-" .. level_name
  local surface = game.create_surface(surface_name, {
    default_enable_all_autoplace_controls = false,
    property_expression_names = {
      cliffiness = 0,
      ["enemy-base-frequency"] = 0,
      ["enemy-base-radius"] = 0,
      ["enemy-base-intensity"] = 0,
    },
    autoplace_settings = {
      entity = { treat_missing_as_default = false },
      tile = { treat_missing_as_default = false },
      decorative = { treat_missing_as_default = false },
    },
    width = MAP_W * 2 + 4,
    height = MAP_H * 2 + 4,
    starting_area = 0,
  })

  -- Request chunk generation for the play area
  surface.request_to_generate_chunks({x = MAP_W / 2, y = MAP_H / 2}, 3)
  surface.force_generate_chunk_requests()

  -- Fill the entire surface with void tiles (surface is centered on origin)
  local half_w = math.ceil((MAP_W * 2 + 4) / 2)
  local half_h = math.ceil((MAP_H * 2 + 4) / 2)
  local tiles = {}
  for y = -half_h, half_h do
    for x = -half_w, half_w do
      tiles[#tiles + 1] = {name = "nh-void", position = {x = x, y = y}}
    end
  end
  surface.set_tiles(tiles)

  -- Disable day/night cycle - always bright
  surface.always_day = true

  disp.levels[level_name] = {
    surface_name = surface_name,
    grid = {},  -- [y][x] = {tile_idx, ch, color, special}
  }
  disp.entity_map[level_name] = {}

  return surface
end

-- Switch to a dungeon level
function Display.switch_level(level_name, player)
  local disp = storage.nh_display
  local surface = Display.get_or_create_level(level_name)
  disp.current_level = level_name

  if player then
    local pos = disp.player_pos
    player.teleport({x = pos.x + 0.5, y = pos.y + 0.5}, surface)
  end

  return surface
end

-- Get current surface
function Display.get_current_surface()
  local disp = storage.nh_display
  if not disp.current_level then return nil end
  local level = disp.levels[disp.current_level]
  if not level then return nil end
  return game.surfaces[level.surface_name]
end

-- Destroy entity at a grid position if one exists
local function destroy_entity_at(level_name, x, y)
  local disp = storage.nh_display
  local emap = disp.entity_map[level_name]
  if not emap then return end
  if not emap[y] then return end
  local ent_data = emap[y][x]
  if ent_data and ent_data.entity and ent_data.entity.valid then
    ent_data.entity.destroy()
  end
  if emap[y] then
    emap[y][x] = nil
  end
end

-- Place or update an entity at grid position
local function place_entity(surface, level_name, x, y, entity_name, tint)
  local disp = storage.nh_display
  destroy_entity_at(level_name, x, y)

  local ent = surface.create_entity{
    name = entity_name,
    position = {x = x + 0.5, y = y + 0.5},
    force = "player",
  }

  if ent then
    if tint then
      ent.color = tint
    end

    if not disp.entity_map[level_name][y] then
      disp.entity_map[level_name][y] = {}
    end
    disp.entity_map[level_name][y][x] = {
      entity = ent,
      name = entity_name,
    }
  end

  return ent
end

-- Core function: handle a print_glyph call from NetHack
-- tile_idx = glyph2tile[glyph] index for sprite selection
-- ch = ASCII character, color = color index, special = glyphflags
--
-- NetHack's core already handles visibility via glyph substitution:
--   - Dark rooms get S_darkroom glyph (different tile_idx than lit S_room)
--   - Unlit corridors get S_corr (different tile_idx than S_litcorr)
--   - Stone/rock always gets S_stone tile_idx
-- So we just render the tile_idx entity and get dark/lit distinction for free.
function Display.print_glyph(x, y, tile_idx, ch, color, special)
  local disp = storage.nh_display
  if not disp.current_level then return end

  local level_name = disp.current_level
  local level = disp.levels[level_name]
  local surface = game.surfaces[level.surface_name]
  if not surface then return end

  -- Store grid state
  if not level.grid[y] then level.grid[y] = {} end
  local old = level.grid[y][x]
  level.grid[y][x] = {tile_idx = tile_idx, ch = ch, color = color, special = special}

  -- Skip if nothing changed
  if old and old.tile_idx == tile_idx and old.ch == ch and old.color == color and old.special == special then
    return
  end

  local is_monster = (special and bit32.band(special, MG_MONSTER) ~= 0)
  local is_pet = (special and bit32.band(special, MG_PET) ~= 0)
  local is_detect = (special and bit32.band(special, MG_DETECT) ~= 0)

  -- Determine entity name from tile index
  local ent_name = Display.tile_entity_name(tile_idx)

  -- Determine tint for special effects
  local tint = nil
  if is_pet then
    tint = PET_TINT
  elseif is_detect then
    tint = DETECT_TINT
  end

  -- Handle the player character '@'
  -- NetHack 3.6.7's mapglyph() does NOT set MG_MONSTER in special flags,
  -- so we detect the player by character alone. The player's @ is always
  -- drawn last, so the final @ position is correct.
  if ch == string.byte("@") then
    disp.player_pos = {x = x, y = y}
    surface.set_tiles({{name = "nh-floor", position = {x = x, y = y}}})
    destroy_entity_at(level_name, x, y)
    return
  end

  -- Walls: floor tile underneath + wall entity on top
  if WALL_CHARS[ch] then
    surface.set_tiles({{name = "nh-floor", position = {x = x, y = y}}})
    place_entity(surface, level_name, x, y, ent_name, tint)
    return
  end

  -- Doors: floor tile underneath + door entity on top
  if DOOR_CHARS[ch] then
    surface.set_tiles({{name = "nh-floor", position = {x = x, y = y}}})
    place_entity(surface, level_name, x, y, ent_name, tint)
    return
  end

  -- Stairs: floor tile underneath + stair entity on top
  if STAIR_CHARS[ch] then
    surface.set_tiles({{name = "nh-floor", position = {x = x, y = y}}})
    place_entity(surface, level_name, x, y, ent_name, tint)
    return
  end

  -- Monsters (non-player)
  if is_monster then
    surface.set_tiles({{name = "nh-floor", position = {x = x, y = y}}})
    place_entity(surface, level_name, x, y, ent_name, tint)
    return
  end

  -- Floor and corridor: use tile_idx entity for the sprite.
  -- The core already picks dark vs lit variants (S_darkroom vs S_room,
  -- S_corr vs S_litcorr), so different tile_idx = different sprite.
  if ch == string.byte(".") or ch == string.byte("#") then
    surface.set_tiles({{name = "nh-floor", position = {x = x, y = y}}})
    place_entity(surface, level_name, x, y, ent_name, tint)
    return
  end

  -- Water: } with blue/cyan color
  if ch == string.byte("}") then
    if color == 1 then -- CLR_RED = lava
      surface.set_tiles({{name = "nh-lava", position = {x = x, y = y}}})
    else
      surface.set_tiles({{name = "nh-water", position = {x = x, y = y}}})
    end
    destroy_entity_at(level_name, x, y)
    return
  end

  -- Traps (^)
  if ch == string.byte("^") then
    surface.set_tiles({{name = "nh-floor", position = {x = x, y = y}}})
    place_entity(surface, level_name, x, y, ent_name, tint)
    return
  end

  -- Stone/rock (space character): render the stone tile entity.
  -- The core sends S_stone for all rock — both explored and unexplored.
  -- This matches Qt behavior where all stone is shown as dark rock texture.
  if ch == string.byte(" ") then
    surface.set_tiles({{name = "nh-void", position = {x = x, y = y}}})
    place_entity(surface, level_name, x, y, ent_name, tint)
    return
  end

  -- Items and other visible features (anything above ASCII 32)
  if ch > 32 then
    surface.set_tiles({{name = "nh-floor", position = {x = x, y = y}}})
    place_entity(surface, level_name, x, y, ent_name, tint)
    return
  end
end

-- Clear the entire map display (called on level change)
function Display.clear_map()
  local disp = storage.nh_display
  if not disp.current_level then return end

  local level_name = disp.current_level
  local level = disp.levels[level_name]
  local surface = game.surfaces[level.surface_name]
  if not surface then return end

  -- Destroy all entities
  local emap = disp.entity_map[level_name]
  if emap then
    for y, row in pairs(emap) do
      for x, ent_data in pairs(row) do
        if ent_data.entity and ent_data.entity.valid then
          ent_data.entity.destroy()
        end
      end
    end
  end
  disp.entity_map[level_name] = {}

  -- Reset grid
  level.grid = {}

  -- Fill with void
  local tiles = {}
  for y = 0, MAP_H - 1 do
    for x = 0, MAP_W - 1 do
      tiles[#tiles + 1] = {name = "nh-void", position = {x = x, y = y}}
    end
  end
  surface.set_tiles(tiles)
end

-- Get the player's expected position from the display
function Display.get_player_pos()
  local disp = storage.nh_display
  return disp.player_pos
end

-- Get current level name
function Display.get_current_level()
  local disp = storage.nh_display
  return disp.current_level
end

return Display
